services:
  aws:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    build:
      context: .
      dockerfile: Dockerfile.aws
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
    volumes:
      - "LOCALSTACK_VOLUME_DIR:/var/lib/localstack"
      # - "/var/run/docker.sock:/var/run/docker.sock"
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.rust
volumes:
  LOCALSTACK_VOLUME_DIR:
